'use strict';

const MAX_BALLOTS = 10_000;
const MAX_CANDIDATES = 32;
const MAX_ORGANIZATIONS = 32;
const MAX_SIGNATURES = 32;
const MAX_VECTOR_RECEIPTS = 20_000;
const MAX_VECTOR_DISCLOSURES = 10_000;

module.exports = {
  MAX_BALLOTS,
  MAX_CANDIDATES,
  MAX_ORGANIZATIONS,
  MAX_SIGNATURES,
  MAX_VECTOR_RECEIPTS,
  MAX_VECTOR_DISCLOSURES,
};
